# import turtle
# t = turtle.Turtle()
# t.pencolor('grey')
# t.begin_fill()
# t.fillcolor('grey')
# for i in range(2):
#     t.forward(100)
#     t.right(90)
#     t.forward(50)
#     t.right(90)
# t.end_fill()
# t.begin_fill()
# t.penup()
# t.goto(0,-60)
# t.down()
# t.pencolor('red')
# t.fillcolor('red')
# t.circle(15)
# t.end_fill()
# t.penup()
# t.goto(100,-60)
# t.pendown()
# t.begin_fill()
# t.circle(15)
# t.fillcolor('red')
# t.end_fill()
# # t.penup()
# # t.goto(45,-15)
# # t.pendown()
# # for i in range(4):
# #     t.forward(10)
# #     t.right(90)
# t.penup()
# t.goto(10,0)
# t.pendown()
# t.color('grey')
# t.left(60)
# t.forward(50)
# t.right(60)
# t.forward(25)
# t.right(60)
# t.forward(50)
# t.penup()
# t.goto(47,0)
# t.pendown()
# t.setheading(90)
# t.forward(45)
# turtle.done()



